version: '3.9'
services:
  tofhir-log-server:
    image: srdc/tofhir-log-server:latest
    container_name: dt4h-tofhir-log-server
    hostname: tofhir-log-server
    ports:
      - "6086:8086"
    networks:
      - tofhir-network
    volumes:
      - './tofhir-docker-logs:/usr/local/tofhir/logs'
  tofhir-server:
    image: srdc/tofhir-server:latest
    container_name: dt4h-tofhir-server
    hostname: tofhir
    environment:
      - LOG_SERVICE_ENDPOINT=http://tofhir-log-server:8086/tofhir-logs
      - FHIR_DEFINITIONS_ENDPOINT=http://onfhir:8080/fhir
      - FHIR_REPO_URL=http://onfhir:8080/fhir
      - APP_CONF_FILE=/usr/local/tofhir/conf/docker/tofhir-server.conf
      - CONTEXT_PATH=conf
    ports:
      - "6085:8085"
    networks:
      - tofhir-network
    volumes:
      - './data-ingestion-suite:/usr/local/tofhir/conf'
      - './tofhir-docker-logs:/usr/local/tofhir/logs'
  tofhir-web:
    image: srdc/tofhir-web:dt4h-nginx
    container_name: dt4h-tofhir-web
    ports:
      - "6082:80"
    networks:
      - tofhir-network
networks:
  tofhir-network:
    name: onfhir-network
    external: true
