version: '3.9'

services:
  postgres:
    image: postgres:14.10
    container_name: dt4h-icrc-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: icrc
    volumes:
      - /docker-containers/dt4h/icrc-test/postgresql/data:/var/lib/postgresql/data
    networks:
      - onfhir-network
    ports:
      - "6432:5432"

networks:
  onfhir-network:
    external: true
