services:
  tofhir-server:
    image: srdc/tofhir-server:latest
    container_name: dt4h-tofhir-server
    hostname: tofhir
    environment:
      - FHIR_DEFINITIONS_ENDPOINT=http://onfhir:8080/fhir
      - FHIR_REPO_URL=http://onfhir:8080/fhir
      - APP_CONF_FILE=/usr/local/tofhir/conf/docker/tofhir-server.conf
      - FLUENT_HOST=fluentd
      - CONTEXT_PATH=conf
      - JAVA_OPTIONS=-Xms256m -Xmx7g
    ports:
      - "6085:8085"
    networks:
      - tofhir-network
    volumes:
      - './data-ingestion-suite:/usr/local/tofhir/conf'
      - './tofhir-docker-logs:/usr/local/tofhir/logs'
    healthcheck:
      test: curl --fail --request OPTIONS http://localhost:8085/tofhir || exit 1
      interval: 20s
      timeout: 10s
      retries: 5      
  tofhir-web:
    image: srdc/tofhir-web:dt4h
    container_name: dt4h-tofhir-web
    ports:
      - "6082:80"
    networks:
      - tofhir-network
    depends_on:
      tofhir-server:
        condition: service_healthy      
 # Elasticsearch, Fluentd and Kibana stack for mapping job log management
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    container_name: dt4h-elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms256m -Xmx2g"      
    ports:
      - "9200:9200"
    networks:
      - tofhir-network
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
  fluentd:
    image: srdc/tofhir-fluentd:latest
    container_name: dt4h-fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    environment:
      - FORWARD_PORT=24224
      - HOST=elasticsearch
      - PORT=9200
    networks:
      - tofhir-network
  kibana:
    image: srdc/tofhir-kibana:latest
    container_name: dt4h-kibana
    environment:
      - SERVER_BASEPATH=/dt4h/tofhir/kibana
      - SERVER_REWRITEBASEPATH=false
    ports:
      - "5601:5601"
    networks:
      - tofhir-network
    depends_on:
      - elasticsearch
networks:
  tofhir-network:
    name: onfhir-network
    external: true
volumes:
  elasticsearch_data:
    driver: local